---
include:
  - "app/**/*.rb"
  - "config/**/*.rb"
exclude:
  - "spec/**/*"
  - "vendor/**/*"
  - ".bundle/**/*"
  # - "test/**/*"
require: 
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
  - actiondispatch
domains: []
reporters:
  - standardrb
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins:
  - solargraph-rails
  - solargraph-standardrb
max_files: 5000
